/**
 * scripts/sync-env.ts
 *
 * Reads the root .env and generates mobile/.env from it.
 *
 * Why this is needed:
 *   Expo CLI (Metro bundler) looks for .env in the mobile/ project directory.
 *   There is no Expo config option to redirect it to a parent path.
 *   This script bridges that gap so you only ever edit the root .env.
 *
 * Run manually:   pnpm sync-env
 * Runs auto:      pnpm dev  (via "predev" hook in root package.json)
 */

import * as fs from 'fs';
import * as path from 'path';

const ROOT        = path.resolve(__dirname, '..');
const rootEnvPath = path.join(ROOT, '.env');
const mobileEnvPath = path.join(ROOT, 'mobile', '.env');

if (!fs.existsSync(rootEnvPath)) {
  console.error('❌  Root .env not found. Copy .env.example and fill in values first.');
  process.exit(1);
}

const lines = fs.readFileSync(rootEnvPath, 'utf-8').split('\n');

const mobileLines: string[] = [
  '# ─────────────────────────────────────────────────────────────────────────────',
  '# AUTO-GENERATED — do not edit this file.',
  '# Edit the root .env instead, then run: pnpm sync-env',
  '# ─────────────────────────────────────────────────────────────────────────────',
  '',
];

for (const line of lines) {
  const trimmed = line.trim();

  // Include EXPO_PUBLIC_* vars, GOOGLE_MAPS_API_KEY, and blank lines.
  // Skip comment-only lines from the root file (they don't apply here)
  // and skip any other vars (NODE_ENV, VITE_*, FIREBASE_SERVICE_ACCOUNT_JSON, etc.).
  if (
    trimmed === '' ||
    trimmed.startsWith('EXPO_PUBLIC_') ||
    trimmed.startsWith('GOOGLE_MAPS_API_KEY=')
  ) {
    mobileLines.push(line);
  }
}

fs.writeFileSync(mobileEnvPath, mobileLines.join('\n') + '\n');
console.log('✅  mobile/.env synced from root .env');
