name: Deploy tenant-service

on:
  push:
    branches: [main, release]
    paths:
      - "tenant-service/**"
      - "packages/**"
      - ".github/workflows/deploy-tenant-service.yml"
      - ".github/workflows/_deploy-service.yml"

jobs:
  deploy-dev:
    name: Dev
    if: github.ref == 'refs/heads/main'
    uses: ./.github/workflows/_deploy-service.yml
    with:
      service-name: tenant-service
      ecs-cluster:  saferide-dev
    secrets: inherit

  deploy-prod:
    name: Prod
    if: github.ref == 'refs/heads/release'
    uses: ./.github/workflows/_deploy-service.yml
    with:
      service-name:        tenant-service
      ecs-cluster:         saferide-prod
      deploy-environment:  production
      wait-for-stable:     true
    secrets: inherit
